In [2]:
# import numpy library
import numpy as np


In [5]:
#create random matrix - 2X2
matrix = np.random.randn(2,2)
matrix

array([[-1.59094972, -0.42622259],
       [-0.35600789, -0.02230014]])

In [6]:
#check shape
matrix.shape

(2, 2)

In [7]:
#check data type
matrix.dtype


dtype('float64')

In [13]:
#generate list
l = []
for i in range(1,11):
    l.append(i)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#convert list into numpy array
np_array = np.array(l)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#check array dimension 
np_array.ndim


1

In [18]:
#create matrix with zeroes
np.zeros((2,2), dtype='int')


array([[0, 0],
       [0, 0]])

In [19]:
#create matrix with empty values/zeros
np.empty((2,2), dtype='float')


array([[0., 0.],
       [0., 0.]])

In [22]:
#use range to create matrix
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#use full to fill matrix with any number
np.full((2,2), fill_value=1.1, dtype='float')


array([[1.1, 1.1],
       [1.1, 1.1]])

array([[0., 0.]])