In [2]:
# import numpy library
import numpy as np


In [42]:
#create random matrix - 2X2
matrix = np.random.randn(2,2)
matrix

array([[-0.10560911,  0.1499717 ],
       [-1.53609451,  0.67844565]])

In [6]:
#check shape
matrix.shape

(2, 2)

In [7]:
#check data type
matrix.dtype


dtype('float64')

In [13]:
#generate list
l = []
for i in range(1,11):
    l.append(i)
l

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#convert list into numpy array
np_array = np.array(l)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#check array dimension 
np_array.ndim


1

In [18]:
#create matrix with zeroes
np.zeros((2,2), dtype='int')


array([[0, 0],
       [0, 0]])

In [19]:
#create matrix with empty values/zeros
np.empty((2,2), dtype='float')


array([[0., 0.],
       [0., 0.]])

In [22]:
#use range to create matrix
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#use full to fill matrix with any number
np.full((2,2), fill_value=1.1, dtype='float')


array([[1.1, 1.1],
       [1.1, 1.1]])

In [53]:
#cast float matrix into integer matrix
matrix = np.full((3,2), fill_value = 3.3, dtype='float64')
matrix.astype(dtype='int')

array([[3, 3],
       [3, 3],
       [3, 3]])

In [55]:
#Any arithmetic operations between equal-size matrix can be done
#array multiplication 
arr = np.array([[1,2,3],[4,5,6]])
arr * 2


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [62]:
#Indexing/Slicing
arr = np.arange(1,11)
arr[5:8]

array([1, 2, 3, 4])

In [64]:
#Boolean Indexing
arr_ind = np.array([100, 200, 200, 201, 304, 505])
arr_ind == 200

SyntaxError: invalid syntax (<ipython-input-64-531266781a52>, line 5)